### ISSUE TITLE
Invisible wall

### ISSUE THREAD

**Issue by liekemichielsen** [danielbrouwer08/EWI3620TU_Group_2#102]
Kan de invisible wall aan de bovenkant iets meer naar beneden verplaatst worden? Daardoor is het makkelijker de te verhelpen dat er om levels heen gelopen kan worden.
Ook moet er iets bedacht worden voor de onderkant. Nu kan je tot heel ver naar onderen lopen zonder dat je doorgaat

**Comment by danielbrouwer08** [comment]
Ik ga er nu aan werken
