### ISSUE TITLE
playtester tegen mij: je moet maar net weten dat die checkpoints er zijn...

### ISSUE THREAD

**Issue by sstroobants** [danielbrouwer08/EWI3620TU_Group_2#105]
Ze zijn namelijk niet altijd in beeld en dan loop je er zo langs

**Comment by Ivo2357** [comment]
Ik ga even kijken of ik hier iets aan kan doen

**Comment by Ivo2357** [comment]
Ik weet niet zo goed wat ik hiermee moet, en het lijkt me ook niet zo'n prioriteit, dus ik ga wat anders doen.
