### ISSUE TITLE
Character selection menu

### ISSUE THREAD

**Issue by MatthijsOttenhoff** [danielbrouwer08/EWI3620TU_Group_2#113]
Moeten de dunne en de dikke kabouter nog in

**Comment by MatthijsOttenhoff** [comment]
Ga ik nu mee aan de slag

**Comment by MatthijsOttenhoff** [comment]
Basis met ronddraaiende character staat. Moet nog geoptimaliseerd worden.

**Comment by danielbrouwer08** [comment]
De ronddraaiende kabouters zien er heel goed uit! Er is alleen nu geen optie meer om een andere saveslot te kiezen :S
