### ISSUE TITLE
Steen in tutorial level ligt al beneden

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#118]
Dit vind ik nog een van de raarste bugs :(

**Comment by liekemichielsen** [comment]
Onmogelijk om op deze steen te springen
Afstand iets korter maken?

**Comment by liekemichielsen** [comment]
Ook doet deze waterval heel erg gek

**Comment by danielbrouwer08** [comment]
Hier ga ik later mee verder want snap er heulemaal niks meer van
