### ISSUE TITLE
Kracht van het water moet omhoog voor de players

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#123]
Kracht van het water is te zwak. Vaak kun je naar de overkant komen.

**Comment by sstroobants** [comment]
dit wilden we oplossen door het water je damage te laten doen toch? Zo heb ik t iig wel aangepast nu, zal t zo pushen naar develop

**Comment by sstroobants** [comment]
water doet nu damage, even kijken of dit is wat we willen
