### ISSUE TITLE
Je kunt niet springen als je op een gebouwd blokje staat

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#132]
:(

**Comment by liekemichielsen** [comment]
Bij mij kan dat wel als je maar niet te ver aan de rand staat
Misschien de blokjes nog wat breder maken?

**Comment by liekemichielsen** [comment]
óke laat maar dit kon vanochtend nog, maar nu kan je idd helemaal niet meer springen

**Comment by sstroobants** [comment]
Ik denk dat t weer door die raycasts komt, ik weet dat jullie daar veeeeeel mee hebben zitten kloten dus wilde t even morgenochtend bij jullie neerleggen

**Comment by Ivo2357** [comment]
Fixed
