### ISSUE TITLE
Leaf spawn y offset moet hoger want ze zijn nu niet zichtbaar :(

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#141]
Heb het in meerdere levels gemerkt. Bijvoorbeeld level 1 dan spawnen ze wel alleen net iets onder het water waardoor je ze niet ziet en dat is jammer.

**Comment by sstroobants** [comment]
fix k ff

**Comment by sstroobants** [comment]
uhm in mijn ding spawnen ze gewoon exact goed. Dan moet dat per level gefixt worden door de leafspawner iets hoger te zetten denk k
