### ISSUE TITLE
Level 6 Boot/platform komt niet terug als de switch wordt uitgezet

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#35]
De switch werdt aangezet en ja toen was de boot weg en de puzzel niet meer haalbaar :(

**Comment by Ivo2357** [comment]
fixed met 2 features:
- Als beide spelers meer dan 10 meter links van de boot staan komt de boot automatisch terug naar links
- Als beide spelers meer dan 30 meter links van de rechterswitch staan gaat de rechterswitch automatisch uit

Dit 'reset' de situatie als het ware als beide kabouters aan de linkerkant staan, waardoor het altijd oplosbaar is.
