### ISSUE TITLE
Level 3 Er ligt geen helicap en de berg is beklimbaar zonder skill

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#37]
Titel zegt genoeg

**Comment by liekemichielsen** [comment]
Ook erg onduidelijk hoe je het touw kan gebruiken

**Comment by Ivo2357** [comment]
Ik denk dat de groundedmethode zo wel optimaal is, je kan nu niet meer de berg beklimmen, en wel goed vanaf kleine blokjes springen.
