### ISSUE TITLE
Spawnpunt bij het doodgaan

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#39]
Doordat je spawnt bij de vorige checkpoint gaat het fout indien de laatste checkpoint uit het zicht van de camera raakt. Indien een van de spelers dood gaat vallen beide spelers uit het beeld en is het spel niet meer speelbaar.

**Comment by Ivo2357** [comment]
Beide spelers gaan dood als ze meer dan 100 in x-richting uit elkaar zijn als gevolg van het doodgaan van één van de spelers.
