### ISSUE TITLE
Level 5 is uitspeelbaar zonder wat te hoeven doen

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#40]
Wisten we al maar wou er toch even een bug van maken :P

**Comment by Ivo2357** [comment]
Voornamelijk: het volgende stuk terrein moet alleen te breiken zijn vanaf het hoge platform

**Comment by sstroobants** [comment]
En je blijft haken achter de platforms

**Comment by sstroobants** [comment]
Deze staat ook in de issue hierboven over de moving platforms
