### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by liekemichielsen** [danielbrouwer08/EWI3620TU_Group_2#45]
Wanneer je in single player mode bent, gebruikt je ER voor de dunnen kabouter en OP voor de dikke om items te pakken / te gebruiken.

**Comment by Ivo2357** [comment]
Ik ben nu hiermee bezig

**Comment by Ivo2357** [comment]
Singleplayer doet het, met tab verwissel je gewoon van kabouter.
Verder zijn de controls aangepast naar Daniels advies (dan weet je wie je de schuld moet geven):
Player 1: pijltjes en , . / rightshift
Player 2: wasd en b v c leftshift
(respectievelijk bewegen, item gebruiken, item oppakken/switches, springen en rennen)

Dit is dus ingame niet meer aan te passen, maar wel als je de build opstart bij "input".
