### ISSUE TITLE
Level 3 Touw loslaten lukt niet

### ISSUE THREAD

**Issue by Ivo2357** [danielbrouwer08/EWI3620TU_Group_2#54]
De dunne kabouter kan het touw niet loslaten, de dikke lukt het meestal na een paar keer proberen wel, maar ook dat gaat niet ideaal.

**Comment by liekemichielsen** [comment]
Je kan ook gewoon om deze berg heen lopen :(

**Comment by liekemichielsen** [comment]
Ik ga wel even aan level 3 werken

**Comment by liekemichielsen** [comment]
touw flipt de hele tijd, nu verandert door teleporteren
