### ISSUE TITLE
Level 8 Teleporters en smal pad

### ISSUE THREAD

**Issue by Ivo2357** [danielbrouwer08/EWI3620TU_Group_2#56]
De teleporters zijn lastig te zien. Het pad is misschien ook wat smal.

**Comment by liekemichielsen** [comment]
Het idee was dat het pad smal en 'moeilijk' was

**Comment by liekemichielsen** [comment]
Ik ga hier wel even aan werken :)

**Comment by liekemichielsen** [comment]
-teleporters werken niet in single player mode
-muur moet uitgebreid worden
