### ISSUE TITLE
Checkpoint onthoudt playerNum ipv karakter

### ISSUE THREAD

**Issue by Ivo2357** [danielbrouwer08/EWI3620TU_Group_2#60]
In singleplayer: Dunne kabouter vliegt naar een checkpoint en maakt de checkpoint oranje, switcht van karakter en maakt vervolgens de checkpoint groen. Dikke gaat dood en komt vanzelf bij checkpoint. Niet de bedoeling.

**Comment by liekemichielsen** [comment]
het is ook ineens heel moeilijk om een checkpoint groen te krijgen. Als je er een keer tegen aan loopt wordt hij oranje. Wanneer je er dan met de ander tegenaan loopt wordt hij pas groen als je van karakter wisselt.

**Comment by Ivo2357** [comment]
Kijkt nu naar het gameobject in plaats van de playernum, doet het nu prima
