### ISSUE TITLE
Playercontroller springen bij bergen moet opnieuw naar gekeken worden

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#77]
Als je tegen een muur aanstaat kun je niet springen. 

De raycast is even tijdelijk uitgezet.

**Comment by danielbrouwer08** [comment]
Raycast weer aan deels opgelost nu

**Comment by Ivo2357** [comment]
Je kan nu niet meer tegen bergen aan lopen
