### ISSUE TITLE
Pickupitem popups moeten even een transform.lookat camera krijgen

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#82]
Dan zijn ze altijd zichtbaar wel zo nice

**Comment by liekemichielsen** [comment]
misschien ook een ding het in het menu dat je uit kan zetten dat die dingen er zijn?

**Comment by danielbrouwer08** [comment]
Ga er nu aan werken

**Comment by Ivo2357** [comment]
Ga ik nu aan werken

**Comment by Ivo2357** [comment]
En done.
