### ISSUE TITLE
De build crasht als het volgende level/storyline moet laden in tutorial

### ISSUE THREAD

**Issue by danielbrouwer08** [danielbrouwer08/EWI3620TU_Group_2#83]
:(

![nietleuk](https://cloud.githubusercontent.com/assets/14161823/12372073/8c387136-bc4a-11e5-859b-abf9cac4433b.png)

**Comment by liekemichielsen** [comment]
Was dit niet al opgelost?

**Comment by danielbrouwer08** [comment]
Jup is opgelost
