### ISSUE TITLE
Golf moet geoptimaliseerd worden

### ISSUE THREAD

**Issue by sstroobants** [danielbrouwer08/EWI3620TU_Group_2#85]

**Comment by liekemichielsen** [comment]
in tutorial level 2 gaat hij iets te hard
in de tussenstukjes mag hij juist weer iets harder denk ik
golf moet ietsje verder terug respawnen

**Comment by liekemichielsen** [comment]
Ik ga wel even kijken naar goede waarden per level

**Comment by liekemichielsen** [comment]
Golf begint voortaan altijd op een afstand van 20 achter

**Comment by liekemichielsen** [comment]
Nog een particle system eraan gehangen om schuim na te bootsen

**Comment by liekemichielsen** [comment]
volgens mij allemaal wel oke nu
