### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by liekemichielsen** [danielbrouwer08/EWI3620TU_Group_2#96]
- items verdwijnen niet na elk level
- als je in single player mode een item gebruikt, gebruikt de niet actieve kabouter zijn item ook

**Comment by sstroobants** [comment]
Ik ga hiermee aan de slag

**Comment by sstroobants** [comment]
items verdwijnen nu bij het bereiken van een checkpoint met zn tweeen

**Comment by sstroobants** [comment]
nu ook in singleplayer alles gefixt
